### ISSUE TITLE
replicated channel inspect returns no output

### ISSUE THREAD

**Issue by RobClenshaw** [replicatedhq/replicated#256]
From version `0.46` of the CLI, `replicated channel inspect <my-channel>` doesn't seem to return any output unless you specify a value for `--output`.

The help text says that `--output=text` is supposed to be the default, but you need to set it explicitly to get any output. Both `text` and `json` seem to work, it's when you don't specify it that you get no output.

**Comment by jdewinne** [comment]
This might be caused by [1047](https://github.com/spf13/cobra/issues/1047)
