### ISSUE TITLE
Using single ip and configuring paths to access different services.

### ISSUE THREAD

**Issue by tinaoberoi** [replicatedhq/replicated#82]
I have multiple services and deployments running, for example:
backed, frontend, prometheus

Is there a way I could provide client with a single ip and configure paths to all other services.
Example: base-ip/backend -> backend (takes the user to service backend)
                 base-ip/monitoring -> prometheus (take the user to service prometheus)

**Comment by dexhorthy** [comment]
Hi @tinaoberoi  -- thanks for submitting an issue! Since this is a general question, and not directly related to the Replicated CLI tools, would you mind submitting it on https://help.replicated.com/community instead? Sorry for the confusion, thanks so much.

**Comment by tinaoberoi** [comment]
@dexhorthy noted. Thanks for help.
